### ISSUE TITLE
Game crashes because of this mod, and i have no idea why.

### ISSUE THREAD

**Issue by josephmother348832** [MysticMods/MysticalLib#32]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.62_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre158_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  McLib core mod (mclib-1.0.3-1.12.2.jar)
  StackUpCore (StackUp-0.2.3.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 11/13/19 7:47 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at epicsquid.mysticallib.util.MirrorHelper.setFinalValue(MirrorHelper.java:10)
	at epicsquid.mysticallib.util.MirrorHelper.setStaticFinalValue(MirrorHelper.java:24)
	at epicsquid.mysticalworld.init.ModItems.registerItems(ModItems.java:113)
	at epicsquid.mysticalworld.RegistryManager.init(RegistryManager.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_265_RegistryManager_init_RegisterContentEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at epicsquid.mysticallib.LibRegistry.initAll(LibRegistry.java:83)
	at epicsquid.mysticallib.proxy.CommonProxy.preInit(CommonProxy.java:14)
	at epicsquid.mysticallib.proxy.ClientProxy.preInit(ClientProxy.java:24)
	at epicsquid.mysticallib.MysticalLib.preInit(MysticalLib.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 452656952 bytes (431 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 35 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version           | Source                                        | Signature                                |
	|:----- |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCH   | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| UCH   | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | creativecoredummy   | 1.0.0             | minecraft.jar                                 | None                                     |
	| UCH   | littletilescore     | 1.0.0             | minecraft.jar                                 | None                                     |
	| UCH   | obfuscate           | 0.2.6             | minecraft.jar                                 | None                                     |
	| UCH   | damageindicatorsmod | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.0.jar         | None                                     |
	| UCH   | aether_legacy       | 1.4.4             | aether_legacy-1.12.2-v1.4.4.jar               | None                                     |
	| UCH   | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCH   | biomesoplenty       | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
	| UCH   | blockcraftery       | 1.12.2-1.3.1      | blockcraftery-1.12.2-1.3.1.jar                | None                                     |
	| UCH   | calemiutils         | 1.12.2-1.0.11     | calemiutils-1.0.11-MC1.12.2.jar               | None                                     |
	| UCH   | codechickenlib      | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | creativecore        | 1.9.9             | CreativeCore_v1.9.62_mc1.12.2.jar             | None                                     |
	| UCH   | foodexpansion       | 1.3               | FoodExpansion1.3.3-1.12.2.jar                 | None                                     |
	| UCH   | cfm                 | 6.3.1             | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| UCH   | cgm                 | 0.15.2            | guns-0.15.2-1.12.2.jar                        | None                                     |
	| UCH   | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| UCH   | jei                 | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| UCH   | littletiles         | 1.5.0             | LittleTiles_v1.5.0-pre158_mc1.12.2.jar        | None                                     |
	| UCH   | mclib               | 1.0.3             | mclib-1.0.3-1.12.2.jar                        | None                                     |
	| UCH   | metamorph           | 1.1.9             | metamorph-1.1.9-1.12.2.jar                    | None                                     |
	| UCH   | moreexplosives      | 1.0.2             | More+Explosives+V1.0.2.jar                    | None                                     |
	| UCH   | roots               | 1.12.2-3.0.21     | Roots-1.12.2-3.0.21.jar                       | None                                     |
	| UCH   | mysticalworld       | 1.12.2-1.5.0      | mysticalworld-1.12.2-1.5.0.jar                | None                                     |
	| UCH   | nei                 | 2.4.3             | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | patchouli           | 1.0-20            | Patchouli-1.0-20.jar                          | None                                     |
	| UCH   | stackup             | 0.2.3             | StackUp-0.2.3.jar                             | None                                     |
	| UCH   | stupidthings        | 1.1.5             | Stupid+Things-1.12.X-1.1.5.jar                | None                                     |
	| UCH   | vehicle             | 0.41.1            | vehicle-mod-0.41.1-1.12.2.jar                 | None                                     |
	| UCH   | waystones           | 4.0.72            | Waystones_1.12.2-4.0.72.jar                   | None                                     |
	| UCH   | xaerominimap        | 1.17.6            | Xaeros_Minimap_1.17.6_Forge_1.12.jar          | None                                     |
	| UCEE  | mysticallib         | 1.12.2-1.4.0      | mysticallib-1.12.2-1.4.0.jar                  | None                                     |
	| UD    | mclib_core          | 1.0.3             | minecraft.jar                                 | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.62_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre158_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
McLib core mod (mclib-1.0.3-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
StackUpCore (StackUp-0.2.3.jar)
  pl.asie.stackup.StackUpTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.10.12' Renderer: 'Intel(R) HD Graphics 6000'

**Comment by Bluberry-Kat** [comment]
the version of forge you're using is almost a year out-of-date.
[update forge here and get back to us if it continues crashing.](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html)
