### ISSUE TITLE
Mysticallib crashes my game.

### ISSUE THREAD

**Issue by HowardBrook** [MysticMods/MysticalLib#33]
I downloaded a bunch of mods and that's the only library that dosn't work as soon as forge gets to it, it crashes ;/

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  DLFMLCorePlugin (Dynamic-Lights-Mod-1.12.2.jar)
  Quark Plugin (Quark-Mod-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  BetterFoliageLoader (Better-Foliage-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/8/20 4:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)
Caused by: java.lang.NoClassDefFoundError: epicsquid/mysticallib/block/BlockFenceGateBase
	at epicsquid.roots.init.ModBlocks.registerBlocks(ModBlocks.java:113)
	at epicsquid.roots.RegistryManager.init(RegistryManager.java:31)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_744_RegistryManager_init_RegisterContentEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at epicsquid.mysticallib.LibRegistry.initAll(LibRegistry.java:83)
	at epicsquid.mysticallib.proxy.CommonProxy.preInit(CommonProxy.java:14)
	at epicsquid.mysticallib.proxy.ClientProxy.preInit(ClientProxy.java:24)
	at epicsquid.mysticallib.MysticalLib.preInit(MysticalLib.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: epicsquid.mysticallib.block.BlockFenceGateBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 49 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 326983144 bytes (311 MB) / 2617245696 bytes (2496 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version         | Source                                      | Signature                                |
	|:----- |:--------------------------- |:--------------- |:------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                   | 1.12.2          | minecraft.jar                               | None                                     |
	| LCH   | mcp                         | 9.42            | minecraft.jar                               | None                                     |
	| LCH   | FML                         | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | forge                       | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | dsurroundcore               | 3.5.4.3         | minecraft.jar                               | None                                     |
	| LCH   | baubles                     | 1.5.2           | Baubles-1.12-1.5.2.jar                      | None                                     |
	| LCH   | astralsorcery               | 1.10.20         | astralsorcery-1.12.2-1.10.20.jar            | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | jei                         | 4.15.0.293      | jei_1.12.2-4.15.0.293.jar                   | None                                     |
	| LCH   | quark                       | r1.6-177        | Quark-Mod-1.12.2.jar                        | None                                     |
	| LCH   | autoreglib                  | 1.3-32          | AutoRegLib-1.3-32.jar                       | None                                     |
	| LCH   | forgelin                    | 1.8.3           | Shadowfacts-Forgelin-1.12.2.jar             | None                                     |
	| LCH   | betterfoliage               | 2.2.0           | Better-Foliage-Mod-1.12.2.jar               | None                                     |
	| LCH   | bibliocraft                 | 2.4.5           | BiblioCraft-Mod-1.12.2.jar                  | None                                     |
	| LCH   | biomesoplenty               | 7.0.1.2444      | Biomes-O-Plenty-Mod-1.12.2.jar              | None                                     |
	| LCH   | coralreef                   | 2.0             | CoralReef-2.5-1.12.2.jar                    | None                                     |
	| LCH   | darknesslib                 | 1.0.0           | DarknessLib-1.12.2-1.0.0.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | ptrmodellib                 | 1.0.4           | PTRLib-1.0.4.jar                            | None                                     |
	| LCH   | props                       | 2.6.3           | DecoCraft-Mod-1.12.2.jar                    | None                                     |
	| LCH   | dynamiclights               | 1.4.9           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_onfire        | 1.0.7           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_creepers      | 1.0.6           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_dropitems     | 1.1.0           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_entityclasses | 1.0.1           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_mobequipment  | 1.1.0           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_flamearrows   | 1.0.1           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_floodlights   | 1.0.3           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_otherplayers  | 1.0.9           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | dynamiclights_theplayer     | 1.1.3           | Dynamic-Lights-Mod-1.12.2.jar               | None                                     |
	| LCH   | ebwizardry                  | 4.2.7           | ElectroblobsWizardry-4.2.7-MC1.12.2.jar     | None                                     |
	| LCH   | felling                     | 1.4.1           | felling-1.4.1-1.12.x.jar                    | None                                     |
	| LCH   | grue                        | 1.6.0           | Grue-1.12.2-1.6.0.jar                       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | llibrary                    | 1.7.18          | LLibrary-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                  | 1.7.0           | Ice-and-Fire-Mod-1.12.2.jar                 | None                                     |
	| LCH   | jaff                        | 1.7_for_1.12    | JustAFewFish-1.7_for_1.12.jar               | None                                     |
	| LCH   | roots                       | 1.12.2-3.0.21   | Roots-1.12.2-3.0.21.jar                     | None                                     |
	| LCH   | mysticalworld               | 1.12.2-1.6.1    | mysticalworld-1.12.2-1.6.1.jar              | None                                     |
	| LCH   | harvestcraft                | 1.12.2zb        | Pam's+HarvestCraft+1.12.2zf.jar             | None                                     |
	| LCH   | patchouli                   | 1.0-20          | Patchouli-1.0-20.jar                        | None                                     |
	| LCH   | roguelike                   | 1.8.0           | Roguelike-Dungeons-Mod-1.12.2.jar           | None                                     |
	| LCH   | tombstone                   | 3.6.4           | tombstone-3.6.4-1.12.2.jar                  | None                                     |
	| LCH   | torohealthmod               | 1.12.2-11       | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar | None                                     |
	| LCH   | twilightforest              | 3.9.888         | Twilight-Forest-Mod-1.12.2.jar              | None                                     |
	| LCH   | ultimate_unicorn_mod        | 1.5.16          | Ultimate-Unicorn-Mod-1.12.2.jar             | None                                     |
	| LCH   | vampirism                   | 1.5.4           | Vampirism-Mod-1.12.2.jar                    | None                                     |
	| LCH   | teamlapen-lib               | 1.5.4           | Vampirism-Mod-1.12.2.jar                    | None                                     |
	| LCH   | wearablebackpacks           | 3.1.3           | Wearable-Backpacks-Mod-1.12.2.jar           | None                                     |
	| LCH   | worldedit                   | 6.1.10-SNAPSHOT | WorldEdit-1.12.2.jar                        | None                                     |
	| LCH   | xaerominimap                | 1.19.4          | Xaeros-Minimap-Mod-1.12.2.jar               | None                                     |
	| LCH   | orelib                      | 3.6.0.1         | OreLib-1.12.2-3.6.0.1.jar                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                   | 3.5.4.3         | Dynamic-Surroundings-Mod-1.12.2.jar         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCE   | mysticallib                 | 1.12.2-1.3.6    | mysticallib-1.12.2-1.3.6.jar                | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Shadowfacts-Forgelin-1.12.2.jar)
  
DLFMLCorePlugin (Dynamic-Lights-Mod-1.12.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
Quark Plugin (Quark-Mod-1.12.2.jar)
  vazkii.quark.base.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
BetterFoliageLoader (Better-Foliage-Mod-1.12.2.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 430.64
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by GreyMario** [comment]
Have you considered... downloading the latest version of MysticalLib?

**Comment by Bluberry-Kat** [comment]
Your version of MysticalLib is a couple months out of date. [Install a more recent version here.](https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/all?filter-game-version=1738749986%3A628)

**Comment by HowardBrook** [comment]
Thank you for the link, I tried a bunch o "curseforge" mysticallib files but non of them worked. now everything works, thank you <3
