### ISSUE TITLE
mysticallib chrashes on startup

### ISSUE THREAD

**Issue by YoutuberNL300** [MysticMods/MysticalLib#39]
### General Information
see title

**To Reproduce:**

1. open twitch
2. start up modpack

**Expected behavior:**
i expect it to start up

***

### Environment Versions
	| State | ID              | Version                 | Source                                             | Signature                                |
	|:----- |:--------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCH   | mcp             | 9.42                    | minecraft.jar                                      | None                                     |
	| LCH   | FML             | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | jei             | 4.15.0.291              | jei_1.12.2-4.15.0.291 (1).jar                      | None                                     |
	| LCH   | quark           | r1.6-177                | Quark-r1.6-177.jar                                 | None                                     |
	| LCH   | autoreglib      | 1.3-32                  | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCH   | crafttweaker    | 4.1.20                  | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCH   | ctgui           | 1.0.0                   | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCH   | crafttweakerjei | 2.0.3                   | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCH   | limelib         | 1.7.12                  | limelib-1.12.2-1.7.12.jar                          | None                                     |
	| LCH   | furnus          | 2.1.8                   | furnus-1.12.2-2.1.8.jar                            | None                                     |
	| LCH   | hopperducts     | 1.5                     | hopperducts-mc1.12-1.5.jar                         | None                                     |
	| LCH   | roots           | 1.12.2-3.0.26           | Roots-1.12.2-3.0.26.jar                            | None                                     |
	| LCH   | mysticalworld   | 1.12.2-1.3.2            | MysticWorld-1.12.2-1.3.2.jar                       | None                                     |
	| LCH   | openglider      | @VERSION@               | OpenGlider-1.12.1-1.1.0.jar                        | None                                     |
	| LCH   | harvestcraft    | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LCH   | patchouli       | 1.0-20                  | Patchouli-1.0-20.jar                               | None                                     |
	| LCH   | redstonepaste   | 1.7.5                   | redstonepaste-mc1.12-1.7.5.jar                     | None                                     |
	| LCH   | sereneseasons   | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| LCH   | simplecore      | 1.7.3.4                 | simplecore-1.12.2-1.7.3.4.jar                      | None                                     |
	| LCH   | simpleores      | 1.11.2.2                | simpleores-1.12.2-1.11.2.2.jar                     | None                                     |
	| LCH   | storagenetwork  | 1.12.1-1.0.15           | SimpleStorageNetwork-1.12.1-1.0.15.jar             | None                                     |
	| LCH   | tetra           | 0.32.1                  | tetra-1.12.2-0.32.1.jar                            | None                                     |
	| LCH   | structurize     | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
	| LCH   | minecolonies    | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |
	| LCE   | mysticallib     | 1.12.2-1.3.8            | mysticallib-1.12.2-1.3.8.jar                       | None                                     |

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 4/23/20 5:38 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)
Caused by: java.lang.NoSuchMethodError: epicsquid.mysticallib.LibRegistry.addSlabPair(Lnet/minecraft/block/material/Material;Lnet/minecraft/block/SoundType;FLjava/lang/String;Lnet/minecraft/block/state/IBlockState;[Lnet/minecraft/block/Block;Lnet/minecraft/creativetab/CreativeTabs;)V
	at epicsquid.roots.init.ModBlocks.variants(ModBlocks.java:173)
	at epicsquid.roots.init.ModBlocks.registerBlocks(ModBlocks.java:114)
	at epicsquid.roots.RegistryManager.init(RegistryManager.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_392_RegistryManager_init_RegisterContentEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at epicsquid.mysticallib.LibRegistry.initAll(LibRegistry.java:83)
	at epicsquid.mysticallib.proxy.CommonProxy.preInit(CommonProxy.java:14)
	at epicsquid.mysticallib.proxy.ClientProxy.preInit(ClientProxy.java:24)
	at epicsquid.mysticallib.MysticalLib.preInit(MysticalLib.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1317411360 bytes (1256 MB) / 1654652928 bytes (1578 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8g -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version                 | Source                                             | Signature                                |
	|:----- |:--------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft       | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCH   | mcp             | 9.42                    | minecraft.jar                                      | None                                     |
	| LCH   | FML             | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge           | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | jei             | 4.15.0.291              | jei_1.12.2-4.15.0.291 (1).jar                      | None                                     |
	| LCH   | quark           | r1.6-177                | Quark-r1.6-177.jar                                 | None                                     |
	| LCH   | autoreglib      | 1.3-32                  | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCH   | crafttweaker    | 4.1.20                  | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCH   | ctgui           | 1.0.0                   | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCH   | crafttweakerjei | 2.0.3                   | CraftTweaker2-1.12-4.1.20.562.jar                  | None                                     |
	| LCH   | limelib         | 1.7.12                  | limelib-1.12.2-1.7.12.jar                          | None                                     |
	| LCH   | furnus          | 2.1.8                   | furnus-1.12.2-2.1.8.jar                            | None                                     |
	| LCH   | hopperducts     | 1.5                     | hopperducts-mc1.12-1.5.jar                         | None                                     |
	| LCH   | roots           | 1.12.2-3.0.26           | Roots-1.12.2-3.0.26.jar                            | None                                     |
	| LCH   | mysticalworld   | 1.12.2-1.3.2            | MysticWorld-1.12.2-1.3.2.jar                       | None                                     |
	| LCH   | openglider      | @VERSION@               | OpenGlider-1.12.1-1.1.0.jar                        | None                                     |
	| LCH   | harvestcraft    | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LCH   | patchouli       | 1.0-20                  | Patchouli-1.0-20.jar                               | None                                     |
	| LCH   | redstonepaste   | 1.7.5                   | redstonepaste-mc1.12-1.7.5.jar                     | None                                     |
	| LCH   | sereneseasons   | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| LCH   | simplecore      | 1.7.3.4                 | simplecore-1.12.2-1.7.3.4.jar                      | None                                     |
	| LCH   | simpleores      | 1.11.2.2                | simpleores-1.12.2-1.11.2.2.jar                     | None                                     |
	| LCH   | storagenetwork  | 1.12.1-1.0.15           | SimpleStorageNetwork-1.12.1-1.0.15.jar             | None                                     |
	| LCH   | tetra           | 0.32.1                  | tetra-1.12.2-0.32.1.jar                            | None                                     |
	| LCH   | structurize     | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar            | None                                     |
	| LCH   | minecolonies    | 1.12.2-0.11.804-RELEASE | minecolonies-1.12.2-0.11.804-RELEASE-universal.jar | None                                     |
	| LCE   | mysticallib     | 1.12.2-1.3.8            | mysticallib-1.12.2-1.3.8.jar                       | None                                     |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12028.2' Renderer: 'Radeon RX 580 Series'

**Comment by GreyMario** [comment]
Please update MysticalLib (and Mystical World, while you're at it.)

In the future, please double-check that you also update any Required Dependencies a mod has when you update a mod.

**Comment by noobanidus** [comment]
Unfortunately I haven't been able to get to the bottom of why the dependencies aren't being properly respected, and why these errors are triggering before the dependencies resolve and put up an alert saying "you need a newer version". 

In this case, GreyMario is 100% correct -- you need to update Mystical World and Mystical Lib.

**Comment by notcrimson** [comment]
i have the same problem but my mythicallib is up to date to 1.7.10 and mythicalworld is 1.7.1 but cant launch roots(Roots-1.12.2-3.0.28 version)

**Comment by noobanidus** [comment]
@notcrimson Please file a separate issue with the crash report. Even if your error is the same, commenting on a closed issue won't really help. Please post your crash report on PasteBin or Gist and file a new one.
