### ISSUE TITLE
Crash while loading minecraft

### ISSUE THREAD

**Issue by Somebody139** [MysticMods/MysticalLib#47]
heres the full crash:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  No More Glowing Pots (nomoreglowingpots-1.0.jar)
  FutureMC (future-mc-1.12.2-0.2.4.1.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 9/13/20 3:17 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)
Caused by: java.lang.NoSuchMethodError: epicsquid.mysticallib.LibRegistry.addSlabPair(Lnet/minecraft/block/material/Material;Lnet/minecraft/block/SoundType;FLjava/lang/String;Lnet/minecraft/block/state/IBlockState;[Lnet/minecraft/block/Block;ZLnet/minecraft/creativetab/CreativeTabs;)V
	at epicsquid.mysticalworld.init.ModBlocks.variants(ModBlocks.java:112)
	at epicsquid.mysticalworld.init.ModBlocks.registerBlocks(ModBlocks.java:72)
	at epicsquid.mysticalworld.RegistryManager.init(RegistryManager.java:23)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_465_RegistryManager_init_RegisterContentEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at epicsquid.mysticallib.LibRegistry.initAll(LibRegistry.java:74)
	at epicsquid.mysticallib.proxy.CommonProxy.preInit(CommonProxy.java:17)
	at epicsquid.mysticallib.proxy.ClientProxy.preInit(ClientProxy.java:25)
	at epicsquid.mysticallib.MysticalLib.preInit(MysticalLib.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1703446128 bytes (1624 MB) / 2214592512 bytes (2112 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                      | Signature                                |
	|:----- |:----------------- |:----------------- |:------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2            | minecraft.jar                               | None                                     |
	| LCH   | mcp               | 9.42              | minecraft.jar                               | None                                     |
	| LCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | forge             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | creativecoredummy | 1.0.0             | minecraft.jar                               | None                                     |
	| LCH   | srm-hooks         | 1.12.2-1.0.0      | minecraft.jar                               | None                                     |
	| LCH   | jei               | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                   | None                                     |
	| LCH   | athenaeum         | 1.12.2-1.19.1     | athenaeum-1.12.2-1.19.1.jar                 | None                                     |
	| LCH   | quark             | r1.6-177          | Quark-r1.6-177.jar                          | None                                     |
	| LCH   | autoreglib        | 1.3-32            | AutoRegLib-1.3-32.jar                       | None                                     |
	| LCH   | bookshelf         | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | chaotica          | 4.8.5             | Chaotica_v4.8.51fixed[1.12.2].jar           | None                                     |
	| LCH   | chiselsandbits    | 14.33             | chiselsandbits-14.33.jar                    | None                                     |
	| LCH   | opframe           | 1.4.0             | OnlinePicFrame_v1.4.40_mc1.12.2.jar         | None                                     |
	| LCH   | creativecore      | 1.9.9             | CreativeCore_v1.9.90_mc1.12.2.jar           | None                                     |
	| LCH   | dropt             | 1.12.2-1.18.0     | dropt-1.12.2-1.18.0.jar                     | None                                     |
	| LCH   | elementalmastery  | 1.3               | elementalmastery-1.3.1.jar                  | None                                     |
	| LCH   | eplus             | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | forgelin          | 1.8.4             | Forgelin-1.8.4.jar                          | None                                     |
	| LCH   | futuremc          | 0.2.4.1           | future-mc-1.12.2-0.2.4.1.jar                | None                                     |
	| LCH   | infernalmobs      | 1.7.6             | InfernalMobs-1.12.2.jar                     | None                                     |
	| LCH   | mantle            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                    | None                                     |
	| LCH   | llibrary          | 1.7.19            | llibrary-1.7.19-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | mowziesmobs       | 1.5.8             | mowziesmobs-1.5.8.jar                       | None                                     |
	| LCH   | mysticalworld     | 1.12.2-1.7.1      | mysticalworld-1.12.2-1.7.1.jar              | None                                     |
	| LCH   | patchouli         | 1.0-20            | Patchouli-1.0-20.jar                        | None                                     |
	| LCH   | placeableitems    | 3.3               | placeableitems-3.3.jar                      | None                                     |
	| LCH   | pyrotech          | 1.12.2-1.4.33     | pyrotech-1.12.2-1.4.33.jar                  | None                                     |
	| LCH   | roughmobs         | 2.0.0             | roughmobs2-1.12.2_2.0.15.jar                | None                                     |
	| LCH   | secretroomsmod    | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar             | None                                     |
	| LCH   | sereneseasons     | 1.2.18            | SereneSeasons-1.12.2-1.2.18-universal.jar   | None                                     |
	| LCH   | tconstruct        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar            | None                                     |
	| LCH   | toughasnails      | 3.1.0.139         | ToughAsNails-1.12.2-3.1.0.139-universal.jar | None                                     |
	| LCH   | valiux            | 2.2               | ValiuxReborn-2.2.1.jar                      | None                                     |
	| LCH   | worleycaves       | 1.5.1             | worleycaves-1.5.1.jar                       | None                                     |
	| LCE   | mysticallib       | 1.12.2-1.9.0      | mysticallib-1.12.2-1.9.0.jar                | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
No More Glowing Pots (nomoreglowingpots-1.0.jar)
  zabi.minecraft.nomoreglowingpots.PotionTransformer
FutureMC (future-mc-1.12.2-0.2.4.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.48' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by GreyMario** [comment]
Update MysticalWorld (and other mods that *depend on* MysticalLib and/or MysticalWorld) and try again.
